from .bs4souppage import BeautifulSoupPageGenerator  # noqa F401
from .armorydetails import ArmoryDetailsGenerator  # noqa F401
from .basedetails import BaseDetailsGenerator  # noqa F401
from .keepdetails import KeepStatusGenerator  # noqa F401
from .recruitdetails import RecruitDetailsGenerator  # noqa F401
from .stattable import StatTableGenerator  # noqa F401
from .trainingdetails import TrainingDetailsGenerator  # noqa F401
from .weapontroopdist import WeaponTroopDistTableGenerator  # noqa F401
from .clockbar import ClockBarGenerator  # noqa F401
